[build]
     command = "pnpm run build"
     publish = "dist"
     functions = "netlify/functions"

   [[headers]]
     for = "/*.js"
     [headers.values]
       Content-Type = "application/javascript"

   [[redirects]]
     from = "/*"
     to = "/index.html"
     status = 200